import { Inject, Injectable, Optional } from '@nestjs/common';
import { generateToken } from '../../../common/crypto/crypto.util';
import { loadLuaScripts } from '../../../database/redis/lua-loader';
import { RedisService } from '../../../database/redis/redis.service';

/** DI token for an injectable clock (ms epoch). Tests use it to jump past the TTL. */
export const AUTHZ_CTX_CLOCK = 'AUTHZ_CTX_CLOCK';

/** TTL of an AuthorizeRequestContext (spec §9.1: 5–10 min). Fixed at 10 min; set once, never slid. */
const CONTEXT_TTL_MS = 10 * 60 * 1000;

/**
 * Persisted context of an in-flight `/authorize` request (spec §9.1).
 *
 * `originalState`/`nonce` are the RP's values, kept only to echo back at the final redirect —
 * they are NOT used as the lookup key. The lookup key is `request_id`, generated by the IdP and
 * independent of the RP's `state` (spec §9.1, tech-lead C8).
 */
export interface AuthorizeRequestContext {
  clientId: string;
  redirectUri: string;
  codeChallenge: string;
  scope: string;
  resource?: string;
  originalState?: string;
  nonce?: string;
  createdAt: number;
  expiresAt: number;
}

const ctxKey = (requestId: string): string => `authz_ctx:${requestId}`;

/**
 * Atomic single-use read: return the value and delete the key in one round trip, so two
 * concurrent resumes of the same `request_id` can never both succeed (tech-lead C3). A plain
 * GET+DEL would race between the two commands.
 */
const CONSUME_SCRIPT = {
  name: 'authzCtxConsume',
  numberOfKeys: 1,
  lua: `
local v = redis.call('GET', KEYS[1])
if v then redis.call('DEL', KEYS[1]) end
return v`,
};

type AuthzRedis = { authzCtxConsume(key: string): Promise<string | null> };

/**
 * AuthorizeRequestContext store on Redis (B4.1, spec §9.1).
 *
 * - `create` mints an opaque `request_id` (CSPRNG) decoupled from the RP's `state`, sets the
 *   context with a fixed TTL (no sliding), and returns the id.
 * - `consume` is atomic single-use: the context is deleted the moment it is read.
 */
@Injectable()
export class AuthorizeRequestContextService {
  private readonly now: () => number;

  constructor(
    private readonly redis: RedisService,
    @Optional() @Inject(AUTHZ_CTX_CLOCK) now?: () => number,
  ) {
    this.now = now ?? Date.now;
    loadLuaScripts(redis.client, [CONSUME_SCRIPT]);
  }

  async create(
    data: Omit<AuthorizeRequestContext, 'createdAt' | 'expiresAt'>,
  ): Promise<{ requestId: string; context: AuthorizeRequestContext }> {
    const requestId = generateToken();
    const createdAt = this.now();
    const context: AuthorizeRequestContext = {
      ...data,
      createdAt,
      expiresAt: createdAt + CONTEXT_TTL_MS,
    };
    // PX + NX: set with the TTL atomically; NX guards against the astronomically unlikely id reuse.
    const ok = await this.redis.client.set(
      ctxKey(requestId),
      JSON.stringify(context),
      'PX',
      CONTEXT_TTL_MS,
      'NX',
    );
    if (ok !== 'OK') {
      throw new Error('AuthorizeRequestContext id collision');
    }
    return { requestId, context };
  }

  /** Read-and-delete the context. Returns null when missing/expired/already consumed. */
  async consume(requestId: string): Promise<AuthorizeRequestContext | null> {
    if (!requestId) return null;
    const raw = await (this.redis.client as unknown as AuthzRedis).authzCtxConsume(
      ctxKey(requestId),
    );
    return raw ? (JSON.parse(raw) as AuthorizeRequestContext) : null;
  }
}
