/** Audit actions (spec §10 reference list). */
export enum AuditAction {
  AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_EMAIL_VERIFIED = 'AUTH_EMAIL_VERIFIED',
  AUTH_PASSWORD_RESET = 'AUTH_PASSWORD_RESET',
  SESSION_CREATED = 'SESSION_CREATED',
  SESSION_REVOKED = 'SESSION_REVOKED',
  OAUTH_AUTHORIZE = 'OAUTH_AUTHORIZE',
  OAUTH_CONSENT_GRANTED = 'OAUTH_CONSENT_GRANTED',
  OAUTH_CONSENT_DENIED = 'OAUTH_CONSENT_DENIED',
  TOKEN_ISSUED = 'TOKEN_ISSUED',
  TOKEN_REFRESHED = 'TOKEN_REFRESHED',
  TOKEN_REUSE_DETECTED = 'TOKEN_REUSE_DETECTED',
  TOKEN_REVOKED = 'TOKEN_REVOKED',
  CLIENT_SECRET_CREATED = 'CLIENT_SECRET_CREATED',
  CLIENT_SECRET_ROTATED = 'CLIENT_SECRET_ROTATED',
  CLIENT_SECRET_REVOKED = 'CLIENT_SECRET_REVOKED',
  REDIRECT_URI_CHANGED = 'REDIRECT_URI_CHANGED',
  SIGNING_KEY_CREATED = 'SIGNING_KEY_CREATED',
  SIGNING_KEY_ROTATED = 'SIGNING_KEY_ROTATED',
  ACCOUNT_LINKED = 'ACCOUNT_LINKED',
  ACCOUNT_UNLINKED = 'ACCOUNT_UNLINKED',
  ADMIN_CLIENT_CREATED = 'ADMIN_CLIENT_CREATED',
  ADMIN_CLIENT_UPDATED = 'ADMIN_CLIENT_UPDATED',
}

/** Actions that must raise a separate alert (spec §10: reuse, key rotation, admin control-plane). */
export const ALERT_ACTIONS: ReadonlySet<AuditAction> = new Set([
  AuditAction.TOKEN_REUSE_DETECTED,
  AuditAction.SIGNING_KEY_ROTATED,
  AuditAction.CLIENT_SECRET_CREATED,
  AuditAction.CLIENT_SECRET_ROTATED,
  AuditAction.CLIENT_SECRET_REVOKED,
  AuditAction.REDIRECT_URI_CHANGED,
  AuditAction.ADMIN_CLIENT_CREATED,
  AuditAction.ADMIN_CLIENT_UPDATED,
]);
